### ISSUE TITLE
Web.config include nukes the project

### ISSUE THREAD

**Issue by jamiehowarth0** [Ucommercenet/Avenue-Clothing-For-Umbraco#57]
The package, once built, contains the web.config file from the root of the AvenueClothing project.
This overrides Umbraco's web.config and causes the site to error immediately after installation.

**Comment by DavidKelemen** [comment]
This should be fixed per #58  (https://github.com/Ucommercenet/Avenue-Clothing-For-Umbraco/releases/tag/8.0.0.20281)

**Comment by estei** [comment]
I am going to close this one.

Please reopen if it shouldn't have been closed :-)
