### ISSUE TITLE
'Product' does not contain a definition for 'PriceInclTax'

### ISSUE THREAD

**Issue by bjornnorlen** [Ucommercenet/Avenue-Clothing-For-Umbraco#62]
After I've downloaded, extracted the files and built the solution i get build error in several files, for example HomepageCatalogController.cs, where it states that "'Product' does not contain a definition for 'PriceInclTax' and no accessible extension method 'PriceInclTax' accepting a first argument of type 'Product' could be found". The product class seems to be generated from metadata, there is no such class in the solution. I receive the same error for the following:
 - PriceInclTax
 - Taxes
 - FieldDefinitions
 - DisplayName

![image](https://user-images.githubusercontent.com/19406378/98381810-b1f19380-204a-11eb-8554-6dd29aa0dca3.png)

**Steps to recreate**
- Download the project as a zip-file
- Extraxt the 'Avenue-Clothing-For-Umbraco-develop' folder
 - Open the AvenueClothing.sln in Visual Studio
 - Build the solution 

Any idea why this happens?

**Comment by DavidKelemen** [comment]
Hi Björn!

Have you downloaded the repository from the develop or the master branch? The develop branch contains WIP changes, and will often not work without a matching (unreleased) version of Ucommerce. The error seems related to upcoming breaking changes we're introducing to Ucommerce, so downloading from master instead should get rid of the error.

Perhaps we should switch the default branch of the solution to master, I can see how this is easy to miss :/

**Comment by bjornnorlen** [comment]
@DavidKelemen Thanks for the quick response. Switching to master solved the issues, thank you. Yeah, or maybe include it as a step in the Readme? :)
