### ISSUE TITLE
Installing Avenue creates error with AvenueClothing.Search.AvenueProductIndexDefinition

### ISSUE THREAD

**Issue by Superhands89** [Ucommercenet/Avenue-Clothing-For-Umbraco#63]
I installed a blank version of Umbraco 8.6.3, and then installed the latest Ucommerce package from the packages section in the back end. Everything is working fine at this stage, but when i install the "Avenue_Clothing_Umbraco8_8.0.0.20281.zip" file as per the instructions on this repo, i get a broken site with following error...

Could not convert string 'AvenueClothing.Search.AvenueProductIndexDefinition, AvenueClothing' to a type

Have i misunderstood or missed a step required to get the demo store up and running? I also tried this with other versions of umbraco 8 and same effect.

(Using SQL Server Express, VS 2019, Chrome)

**Comment by DavidKelemen** [comment]
Hi @Superhands89, 

Where do you get your Avenue_Clothing_Umbraco8_8.0.0.20281 package from? Is it from the repo? If so, you will need to switch over to the master branch before generating a package (the develop branch is WIP and it requires a yet unreleased version of Ucommerce). 

You can also download the Avenue Clothing package from our website: https://download.ucommerce.net/releases/Avenue_Clothing_Umbraco8_8.0.0.20281.zip

The type from the error comes from the avenue clothing package, so it seems that the installation failed. If the package from above gets you the same error, can you check that the bin folder of your website contains an assembly called "AvenueClothing.dll"?

**Comment by Superhands89** [comment]
@DavidKelemen ah that might be the issue yes, i was using this dev branch. cheers

**Comment by estei** [comment]
Looks like you have gotten this issue fixed, so I am going to go ahead and close.

Please reopen if not :-)
