### ISSUE TITLE
Installing Avenue Clothing in Visual Studio 2019

### ISSUE THREAD

**Issue by maxwhite** [Ucommercenet/Avenue-Clothing-For-Umbraco#84]
Hi, I'm trying to install the shop in Visual Studio
but I'm getting errors during build process:

Build started...
1>------ Build started: Project: AvenueClothing, Configuration: Debug Any CPU ------
1>  VS 11 Common Tools not found
1>  VS 12 Common Tools not found
1>  npm WARN package.json someProj@0.0.0 No description
1>  npm WARN package.json someProj@0.0.0 No repository field.
1>  npm WARN package.json someProj@0.0.0 No README data
1>  npm WARN package.json someProj@0.0.0 No license field.
1>  npm WARN engine gulp-sass@4.1.1: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
1>  npm WARN engine request@2.88.2: wanted: {"node":">= 6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
1>  npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
1>  npm WARN engine har-validator@5.1.5: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine string-width@3.1.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine find-up@3.0.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine get-caller-file@2.0.5: wanted: {"node":"6.* || 8.* || >= 10.*"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine camelcase@5.3.1: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine locate-path@3.0.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine wrap-ansi@5.1.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine p-locate@3.0.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine p-limit@2.3.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN engine p-try@2.2.0: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
1>  npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"5.3.0","npm":"2.13.1"})
1>  
1>  > node-sass@4.14.1 install D:\Avenue\src\node_modules\gulp-sass\node_modules\node-sass
1>  > node scripts/install.js
1>  
1>  'node' is not recognized as an internal or external command,
1>  operable program or batch file.
1>  npm ERR! Windows_NT 10.0.19042
1>  npm ERR! argv "D:\\Avenue\\src\\packages\\Node.js.5.3.0\\node.exe" "D:\\Avenue\\src\\packages\\Npm.js.2.13.1.0\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
1>  npm ERR! node v5.3.0
1>  npm ERR! npm  v2.13.1
1>  npm ERR! code ELIFECYCLE
1>  
1>  npm ERR! node-sass@4.14.1 install: `node scripts/install.js`
1>  npm ERR! Exit status 1
1>  npm ERR! 
1>  npm ERR! Failed at the node-sass@4.14.1 install script 'node scripts/install.js'.
1>  npm ERR! This is most likely a problem with the node-sass package,
1>  npm ERR! not with npm itself.
1>  npm ERR! Tell the author that this fails on your system:
1>  npm ERR!     node scripts/install.js
1>  npm ERR! You can get their info via:
1>  npm ERR!     npm owner ls node-sass
1>  npm ERR! There is likely additional logging output above.
1>  
1>  npm ERR! Please include the following file with any support request:
1>  npm ERR!     D:\Avenue\src\AvenueClothing\npm-debug.log
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073: The command "
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       IF EXIST "%VS110COMNTOOLS%VsDevCmd.bat" (
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       call "%VS110COMNTOOLS%VsDevCmd.bat"
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       ) ELSE (
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       echo VS 11 Common Tools not found
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       )
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       IF EXIST "%VS120COMNTOOLS%VsDevCmd.bat" (
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       call "%VS120COMNTOOLS%VsDevCmd.bat"
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       ) ELSE (
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       echo VS 12 Common Tools not found
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       )
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       set PATH=D:\Avenue\src\packages\Npm.js.2.13.1.0\build\..\tools\;%PATH%
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       "D:\Avenue\src\packages\Npm.js.2.13.1.0\build\..\tools\npm" install
1>D:\Avenue\src\packages\Npm.js.2.13.1.0\build\npm.js.targets(27,5): error MSB3073:       " exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I also tried to run project despite this error but got anothe issue in browser page:

Server Error in '/' Application.
Could not load file or assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' could not be loaded.

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Stack Trace:

[FileLoadException: Could not load file or assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   Ucommerce.SystemHttp.App_Start.PreStartEnableAttributesRoutes.EnableAttributesRoutes() +0

[InvalidOperationException: The pre-application start initialization method EnableAttributesRoutes on type Ucommerce.SystemHttp.App_Start.PreStartEnableAttributesRoutes threw an exception with the following error message: Could not load file or assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +617
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +138
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +163
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +156
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +692

[HttpException (0x80004005): The pre-application start initialization method EnableAttributesRoutes on type Ucommerce.SystemHttp.App_Start.PreStartEnableAttributesRoutes threw an exception with the following error message: Could not load file or assembly 'System.Web.Http.WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +659
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +189

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4330.0

Could you please help ?
Thanks

**Comment by jamiehowarth0** [comment]
Same. Basically it looks like the AvenueClothing project has both Nuget Gulp & NPM packages installed, which interfere with the overall build process - I'm assuming that MSBuild is supposed to be producing a DLL + views, then Gulp to minify & compress JS & CSS, then npm to package it up - this is a totally backwards process, in other words. I'm gonna see if I can work out a buildscript that sorts the order of build out, without relying on the Deploy.cmd task.

**Comment by maxwhite** [comment]
@jamiehowarth0 , could you please share if you find how to fix that issue ?

**Comment by marcvan-dijk** [comment]
Pretty curious on how to fix this as well

**Comment by Berg1989** [comment]
I just tried setting up a clean website with Umbraco and Ucommerce installed.

I then cloned the Avenue-Clothing-For-Umbraco repo.
Rebuilt the solution.
Followed the guide in the readme file for creating a package.
Installed the package on my website.

I didn't find any issues, though.

Could you elaborate on each step you are taking when run into this issue? I am uncertain if I understood the issue completely.

Best regards,
Daniel - Ucommerce Solution Developer
